repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.13.1
  hooks:
  - id: ruff-check
    args: [--fix, --show-fixes, --exit-non-zero-on-fix]
  - id: ruff-format
    name: ruff-format
    description: Run 'ruff format' for extremely fast Python formatting
    entry: ruff format
    language: python
    require_serial: true
    args: []
  - id: ruff
    name: ruff check long-lines
    description: Run ruff check with only E501 Line too long turned on
    args: [--select=E501]
