# Config file for automatic testing at travis-ci.org

dist: xenial
language: python
cache: pip
matrix:
  include:
  # Separate job for linting
    - os: linux
      python: "3.8"
      env: TOXENV=lint
    - os: linux
      python: "3.8"
    - os: linux
      python: "3.8"
    - os: linux
      python: "3.7"
    - os: linux
      python: "3.6"
    - os: linux
      python: "3.5"
    - os: linux
      python: "pypy3"
before_install:
  - pip install -U pip


install:
  - pip install -r requirements-tox.txt
  - pip install -U tox-travis coveralls
script: make tox
after_success: coveralls
