# Config file for automatic testing at travis-ci.org

dist: xenial
language: python
cache: pip
matrix:
  include:
  # Separate job for linting
    - os: linux
      python: "3.8"
      env: TOXENV=lint
  # Separate testing for different marshmallow versions in different jobs to ease debugging
    - os: linux
      python: "3.8"
      env: TOXENV=py38-marshmallow2
    - os: linux
      python: "3.8"
      env: TOXENV=py38-marshmallow3
    # These will test for both versions of marshmallow thanks to tox-travis package
    - os: linux
      python: "3.7"
    - os: linux
      python: "3.6"
    - os: linux
      python: "3.5"
    - os: linux
      python: "2.7"
    - os: linux
      python: "pypy3"
    - os: linux
      python: "pypy"
before_install:
  - pip install -U pip


install:
  - pip install -r requirements-tox.txt
  - pip install -U tox-travis coveralls
script: make tox
after_success: coveralls
